name: ERI
favicon: null
layout_spectrum: 0.7271889748517424
typography_spectrum: 0.4118764507584274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13023513834923506
  lightness: 0.22809780086390674
  saturation: 0.46930806594900787
  rhythmicContrast: 0.5294302958063781
purpose: []
